playplay/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,  name='cart_remove'),
    path('order/', views.order,  name='order'),
    path('order/confirm_order', views.confirm_order, name='confirm_order'),
]

playplay/js_games/urls.py
from django.urls import path
from . import views

app_name = 'js_games'
urlpatterns = [
    path('', views.js_gamse_list, name='js_gamse_list'),
    path('play_game/?<str:game_id>/', views.play_gamse, name='play_game'),
]

playplay/playplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('personnel_hub/', include('personnel_hub.urls')),
    path('reg/', include('auth_app.urls')),
    path('play_games/', include('js_games.urls')),
    path('cart/', include('cart.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playplay/js_games/models.py
from django.db import models


class Game(models.Model):
    js_game_name = models.CharField(max_length=100, verbose_name='Назва гри')
    js_game_file = models.FileField(verbose_name='Шлях гри')
    js_game_image = models.ImageField(upload_to='js_games/', blank=True, null=True, verbose_name='Фото гри')
    js_game_description = models.TextField(blank=True, null=True, verbose_name='Короткий опис гри')
    js_game_enabled = models.BooleanField(default=False, verbose_name='Включити/Вимкнути')
    js_game_width = models.IntegerField(blank=True, null=True, verbose_name='Ширина гри')
    js_game_height = models.IntegerField(blank=True, null=True, verbose_name='Висота')


    def __str__(self):
        return self.js_game_name

playplay/js_games/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from . import models


def index(request: HttpRequest):
    return render(request, 'js_games/base_for_js_games.html')


def js_gamse_list(request: HttpRequest):
    games = models.Game.objects.filter(js_game_enabled=1)
    return render(request, 'js_games/js_games_list.html', {'games': games})


def play_gamse(request: HttpRequest, game_id:str=None):
    game_objct = models.Game.objects.get(pk=game_id)
    game_url = '/static/js_games' + game_objct.js_game_file.url
    game_width = game_objct.js_game_width
    game_height = game_objct.js_game_height
    context = {
        'game_url': game_url,
        'game_width': game_width,
        'game_height': game_height,
    }
    return render(request, 'js_games/base_for_js_games.html', context)

playplay/js_games/templates/js_games/base_for_js_games.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Гра на JavaScript</title>
    <link rel="stylesheet" href="{% static 'css/js_games.css' %}">
</head>
<body>

    <div id="game-container">
        <canvas id="game" width="{{game_width}}" height="{{game_height}}"></canvas>
    </div>
    <button onclick="refreshPage()">Зіграти ще раз</button>
    <script src="{{ game_url }}"></script>
    <script>
        function refreshPage() {
            location.reload();
        }
    </script>
</body>
</html>

playplay/js_games/templates/js_games/js_games_list.html
{% extends 'main_page/index.html' %}
{% load static %}
    {% block categories %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block products %}
    <section class="u-clearfix u-container-align-center u-grey-90 u-section-3" id="carousel_42f3">
      <div class="u-container-align-center u-container-style u-group u-image u-image-1" data-image-width="1980" data-image-height="2400">
        <div class="u-container-layout u-valign-top-lg u-valign-top-md u-valign-top-sm u-valign-top-xl u-container-layout-1">
          <h2 class="u-align-center u-text u-text-body-color u-text-default u-text-1" data-animation-name="customAnimationIn" data-animation-duration="1500">Грай прямо зараз</h2>
        </div>
      </div>
      <div class="u-list u-list-1">
        <div class="u-repeater u-repeater-1">
          {% for game in games %}
          <div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-white u-list-item-1" data-animation-name="customAnimationIn" data-animation-duration="1500">
            <div class="u-container-layout u-similar-container u-container-layout-2">
               {% if game.js_game_image %}
                <a href="{% url 'js_games:play_game' game_id=game.id %}">
                    <img class="u-expanded-width u-image u-image-default u-image-2" src="{{ game.js_game_image.url }}" alt="{{ product.name }" data-image-width="1380" data-image-height="920" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500">
                </a>
               {% else %}
                    <p>Фото/картинка не доступна</p>
                {% endif %}
              <h4 class="u-align-center u-text u-text-2">{{ game.js_game_name }}</h4>
              <p class="u-align-center u-text u-text-3"> {{ game.js_game_description }} </p>
              <a href="{% url 'js_games:play_game' game_id=game.id %}" class="u-border-1  u-border-no-left u-border-no-right u-border-no-top u-border-palette-3-base u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-button-style u-none u-radius-0 u-text-active-black u-text-hover-black u-top-left-radius-0 u-top-right-radius-0 u-btn-1">Грати</a>
            </div>
          </div>
            {% endfor %}
          </div>
        </div>
    </section>
    {% endblock %}