playplay/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,  name='cart_remove'),
    path('order/', views.order,  name='order'),
    path('order/confirm_order', views.confirm_order, name='confirm_order'),
]

playplay/main_page/urls.py
from django.urls import path
from . import views

app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('products_list/?<str:category>', views.products_list, name='products_list'),
    path('product/?<str:product_id>', views.product, name='product'),
    path('about_us/', views.about_us, name='about_us'),
    path('contacts/', views.contacts, name='contacts'),
]

playplay/playplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('personnel_hub/', include('personnel_hub.urls')),
    path('reg/', include('auth_app.urls')),
    path('play_games/', include('js_games.urls')),
    path('cart/', include('cart.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playplay/cart/models.py
from django.db import models

# Create your models here.

playplay/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1,  widget=forms.HiddenInput)
    update = forms.BooleanField(required=False, initial=False,  widget=forms.HiddenInput)

playplay/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from personnel_hub.models import Product, Order, OrderItem
from django.contrib.auth.models import User
from .cart import Cart
from .forms import CartAddProductForm
from django.views.decorators.csrf import csrf_protect
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required


@login_required(login_url='auth_app:login')
def cart_add(request:HttpRequest, product_id:int):
    cart = Cart(request)
    product = Product.objects.get(pk=product_id)
    cart.add(product=product, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')


@login_required(login_url='auth_app:login')
def cart_remove(request:HttpRequest, product_id:int):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


@login_required(login_url='auth_app:login')
def cart_detail(request:HttpRequest):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})


@login_required(login_url='auth_app:login')
def order(request:HttpRequest):
    return render(request, 'cart/order_detail.html')


@csrf_protect
def confirm_order(request: HttpRequest):
    '''
    Підтвердження замовлення, формується обєкт Order та пов'язані з ним OrderItem
    Якщо на складі недостатня кількість товару/товарів - перенеправляємо клієнта на order_problems.html
    Клієнт має в корзині відредагувати замовлення
    '''

    # Перевірка необхідної кількості товару на складі. Формування проблемного контексту

    product_check_list = []
    cart = Cart(request)
    for item in cart:
        product_instance = Product.objects.get(pk=item['product'].id)
        if product_instance.quantity_in_stock < item['quantity']:
            product_check_list.append(product_instance)
    context = {'product_check_list': product_check_list}

    # Визначення сценарію подальшої обробки

    if not(product_check_list): # сценарій, коли товару на складі достатньо, для виконання замовлення
        user_instance = User.objects.get(pk=request.user.id)
        order = Order(
            user=user_instance,
            order_date=now(),
            total_amount=cart.get_total_price()
        )
        order.save()
        order_instance = Order.objects.get(pk=order.id)

        for item in cart:
            product_instance = Product.objects.get(pk=item['product'].id)
            orderitem = OrderItem(
                order=order_instance,
                product=product_instance,
                quantity=item['quantity']
            )
            cart.remove(product_instance)
            orderitem.save()
            product_instance.quantity_in_stock -= item['quantity']
            product_instance.save()
        return render(request, 'cart/confirm_order_done.html')
    else: # сценарій, коли недостатньо товару
        return render(request, 'cart/order_problems.html', context=context)

playplay/cart/templates/cart/confirm_order.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <h3 align="center">Ваше замовлення:</h3>
  <table>
    <thead>
      <tr>
        <th>Зображення</th>
        <th style="padding-right: 10px;">Товар</th>
        <th style="padding-right: 10px;">Кількість</th>
        <th style="padding-right: 10px;">Ціна за шт</th>
        <th style="padding-right: 10px;">Загальна вартість</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'main_page:product' product_id=product.id %}">
                <img src="{{ product.image.url }}" width=150" height="200">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.price }}.грн</td>
            <td class="num">{{ item.total_price }}.грн</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всього</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}.грн</td>
      </tr>
    </tbody>
  </table>
{% csrf_token as csrf_token %}
<a href="{% url 'cart:confirm_order' %}?csrfmiddlewaretoken={{ csrf_token }}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Купити</a>
{% endblock %}

{% block products %}
{% endblock %}

playplay/cart/templates/cart/confirm_order_done.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
  <section class="u-align-center u-clearfix u-palette-3-base u-section-1" id="sec-f7d1">
      <div class="u-clearfix u-gutter-0 u-layout-wrap u-layout-wrap-1">
        <div class="u-gutter-0 u-layout">
          <div class="u-layout-row">
            <div class="u-container-style u-image u-layout-cell u-shape-rectangle u-size-34-lg u-size-38-xl u-size-60-md u-size-60-sm u-size-60-xs u-image-1" data-image-width="1295" data-image-height="1080" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="250">
              <div class="u-container-layout u-container-layout-1"></div>
            </div>
            <div class="u-container-align-left u-container-style u-layout-cell u-shape-rectangle u-size-22-xl u-size-26-lg u-size-60-md u-size-60-sm u-size-60-xs u-layout-cell-2">
              <div class="u-container-layout u-valign-middle u-container-layout-2">
                <h1 class="u-align-left u-text u-text-1" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="250"> Дякуємо за покупку!</h1>
                <p class="u-align-left u-text u-text-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="250">Покупка виконана успішно.<span style="font-style: italic;"></span></p>
                <div class="u-expanded-width-lg u-expanded-width-xl u-list u-list-1">
                    <a href="{% url 'main_page:index' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Повернутись в магазин</a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
{% endblock %}

{% block content %}
{% endblock %}

{% block products %}
{% endblock %}

playplay/cart/templates/cart/detail.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <h3 align="center">Корзина покупок</h3>
  <table>
    <thead>
      <tr>
        <th>Зображення</th>
        <th style="padding-right: 10px;">Товар</th>
        <th style="padding-right: 10px;">Оновити кількість</th>
        <th style="padding-right: 10px;">Видалити</th>
        <th style="padding-right: 10px;">Кількість</th>
        <th style="padding-right: 10px;">Ціна за шт</th>
        <th style="padding-right: 10px;">Загальна вартість</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'main_page:product' product_id=product.id %}">
                <img src="{{ product.image.url }}" width=150" height="200">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Взяти ще один">
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Видалити товар</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.price }}.грн</td>
            <td class="num">{{ item.total_price }}.грн</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всього</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}.грн</td>
      </tr>
    </tbody>
  </table>
    <a href="{% url 'main_page:index' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Продовжити покупки</a>
    <a href="{% url 'cart:order' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Оформити замовлення</a>

{% endblock %}

{% block products %}
{% endblock %}

playplay/cart/templates/cart/order_detail.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <h3 align="center">Ваше замовлення:</h3>
  <table>
    <thead>
      <tr>
        <th>Зображення</th>
        <th style="padding-right: 10px;">Товар</th>
        <th style="padding-right: 10px;">Кількість</th>
        <th style="padding-right: 10px;">Ціна за шт</th>
        <th style="padding-right: 10px;">Загальна вартість</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'main_page:product' product_id=product.id %}">
                <img src="{{ product.image.url }}" width=150" height="200">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.price }}.грн</td>
            <td class="num">{{ item.total_price }}.грн</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всього</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}.грн</td>
      </tr>
    </tbody>
  </table>
{% csrf_token as csrf_token %}
<a href="{% url 'cart:confirm_order' %}?csrfmiddlewaretoken={{ csrf_token }}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Купити</a>
{% endblock %}

{% block products %}
{% endblock %}

playplay/cart/templates/cart/order_problems.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <h3 align="center">Буль-ласка відкоригуйте замовлення</h3>
  <h4>Нажаль по наступним товарам в нас не вистачає необхідної кількості:</h4>
  <table>
    <thead>
      <tr>
        <th style="padding-right: 10px;">Зображення</th>
        <th style="padding-right: 10px;">Товар</th>
        <th style="padding-right: 10px;">Залишок на складі</th>
      </tr>
    </thead>
    <tbody>
      {% for product in product_check_list %}
          <tr>
            <td>
              <a href="{% url 'main_page:product' product_id=product.id %}">
                <img src="{{ product.image.url }}" width=150" height="200">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td style="color: red;">
              {{ product.quantity_in_stock }}
            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
<a href="{% url 'cart:cart_detail' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">В корзину</a>
{% endblock %}

{% block products %}
{% endblock %}