playplay/auth_app/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


app_name = "auth_app"
urlpatterns = [
    path("login/", LoginView.as_view(template_name="auth_app/login.html"),  name="login"),
    path("logout/", LogoutView.as_view(), name="logout" ),
    path("password_change/", PasswordChangeView.as_view(
                template_name="auth_app/password_change_form.html",
                success_url=reverse_lazy("auth_app:password_change_done"),
                ), name="password_change"),
    path("password_change/done/", PasswordChangeDoneView.as_view(
        template_name="auth_app/password_change_done.html"),
        name="password_change_done",
        ),
    path("password_reset/", views.CustomPasswordResetView.as_view(
        template_name='auth_app/password_reset_form.html',
        success_url = reverse_lazy("auth_app:password_reset_done"),
        email_template_name = "auth_app/password_reset_email.html"
        ), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name='auth_app/password_reset_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("auth_app:password_reset_complete"),
            template_name="auth_app/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="auth_app/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("register/", views.register, name="register"),
]

playplay/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,  name='cart_remove'),
    path('order/', views.order,  name='order'),
    path('order/confirm_order', views.confirm_order, name='confirm_order'),
]

playplay/main_page/urls.py
from django.urls import path
from . import views

app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('products_list/?<str:category>', views.products_list, name='products_list'),
    path('product/?<str:product_id>', views.product, name='product'),
    path('about_us/', views.about_us, name='about_us'),
    path('contacts/', views.contacts, name='contacts'),
]

playplay/playplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('personnel_hub/', include('personnel_hub.urls')),
    path('reg/', include('auth_app.urls')),
    path('play_games/', include('js_games.urls')),
    path('cart/', include('cart.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playplay/auth_app/models.py
from django.db import models

# Create your models here.

playplay/auth_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginForm(AuthenticationForm):
    pass


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

playplay/auth_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login
from django.contrib.auth.models import User
from .forms import CustomUserCreationForm
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.conf import settings
from decouple import config

def register(request):
    if request.method == "GET":
        return render(request, "auth_app/auth_registration.html", {"form": CustomUserCreationForm})

    elif request.method == "POST":
        username = request.POST['username']
        if User.objects.filter(username=username).exists():
            return render(
                            request, "auth_app/auth_registration.html",
                            {'error': f'Користувач {username} вже існує. Спробуйте ще раз.',
                             'form': CustomUserCreationForm})
        else:
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                subject = 'Дякуємо за реєстрацію!'
                message = 'Шановний {},\n\nДякуємо, що зареєструвалися на нашому сайті. ' \
                          'Будь ласка, зверніться до нас, якщо у вас виникнуть питання або потрібна допомога.' \
                          '\n\nЗ повагою,\nКоманда сайту {}'.format(user.username, config('PLAYPLAY_URL'))
                from_email = settings.EMAIL_HOST_USER
                to_email = [user.email]
                try:
                    send_mail(subject, message, from_email, to_email)
                except:
                    pass
                return redirect(reverse("main_page:index"))


class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'auth_app/password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')

    def form_valid(self, form):
        login = form.cleaned_data['email']
        try:
            user = User.objects.get(email=login)
            username = user.username
        except User.DoesNotExist:
            username = None
        self.extra_email_context = {
            'username': username,
        }
        return super().form_valid(form)

playplay/auth_app/templates/auth_app/auth_app_base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Reg</title>
   <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
 <div class="top-left-links">
    <a href="{% url 'main_page:index' %}">Головна</a>
  </div>
    <div class="container">
        {% block title %}
            <h2>Логін</h2>
        {% endblock %}

        {% block content %}

        <form method="post">
            {% csrf_token %}
                      {% for field in form %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            <br><br>
        {% endfor %}
            <input type="submit" value="Увійти">
            <p><a href="{% url 'auth_app:register' %}">Зареєструватись</a></p>
            <p><a href="{% url 'auth_app:password_reset' %}">Відновити пароль</a></p>
        </form>

        {% endblock %}
    </div>
</body>
</html>

playplay/auth_app/templates/auth_app/auth_registration.html
{% extends 'auth_app/auth_app_base.html' %}
  {% block title %}
    <h2>Реєстрація нового користувача</h2>
  {% endblock %}

{% block content %}

{% if error %}
    <p>{{ error }}</p>
{% endif %}

 <form method="post" >
        {% csrf_token %}
          {% for field in form %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            <br><br>
        {% endfor %}
        <input type="submit" value="Зареєструватися">
    </form>
{% endblock %}

playplay/auth_app/templates/auth_app/login.html
{% extends 'auth_app/auth_app_base.html' %}

playplay/auth_app/templates/auth_app/password_change_done.html
{% extends 'auth_app/auth_app_base.html' %}

{% block content %}
<h2>Пароль успішно змінено!</h2>
<h2>Перехід на головну сторінку через 3 секунди</h2>
 <script type="text/javascript">
        setTimeout(function() {
            window.location.href = "{% url 'main_page:index' %}";
        }, 3000);  // 3000 мілісекунд = 3 секунд
 </script>
{% endblock %}

playplay/auth_app/templates/auth_app/password_change_form.html
{% extends 'auth_app/auth_app_base.html' %}

  {% block title %}
  {% endblock %}

{% block content %}
    <h2>Зміна пароля {{ request.user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_old_password">Поточний пароль:</label>
            <input type="password" name="old_password" id="id_old_password" required>
            {% if form.old_password.errors %}
                <ul class="errorlist">
                    {% for error in form.old_password.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div>
            <label for="id_new_password1">Новий пароль:</label>
            <input type="password" name="new_password1" id="id_new_password1" required>
            {% if form.new_password1.errors %}
                <ul class="errorlist">
                    {% for error in form.new_password1.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div>
            <label for="id_new_password2">Підтвердження нового пароля:</label>
            <input type="password" name="new_password2" id="id_new_password2" required>
            {% if form.new_password2.errors %}
                <ul class="errorlist">
                    {% for error in form.new_password2.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <input type="submit" value="Змінити пароль">
    </form>
{% endblock %}

playplay/auth_app/templates/auth_app/password_reset_complete.html
{% extends 'auth_app/auth_app_base.html' %}

{% block title %}
<h2>Пароль успішно змінено</h2>

{% endblock %}

{% block content %}
<p align="center"><a href="{% url 'auth_app:login' %}">Login</a></p>
{% endblock %}

playplay/auth_app/templates/auth_app/password_reset_confirm.html
{% extends 'auth_app/auth_app_base.html' %}

{% block title %}
<h2>Введіть новий пароль</h2>
{% endblock %}

{% block content %}


<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Підтвердити">
</form>
{% endblock %}

playplay/auth_app/templates/auth_app/password_reset_done.html
{% extends 'auth_app/auth_app_base.html' %}
{% block title %}
<h3>На Вашу пошту відправлено лист з посиланням, для відновлення пароля</h3>
{% endblock %}
{% block content %}

{% endblock %}

playplay/auth_app/templates/auth_app/password_reset_email.html
Вітання від http://playplay.pythonanywhere.com/
Ви отримали це повідомлення , оскільки ви або хтось інший запитав процедуру відновлення пароля для вашого облікового запису.

{% if username %}
Ім'я користувача: {{ username }}
{% endif %}
Щоб встановити новий пароль, натисніть на наступне посилання або скопіюйте його в адресний рядок браузера
{{ protocol}}://{{ domain }}{% url 'auth_app:password_reset_confirm' uidb64=uid token=token %}

playplay/auth_app/templates/auth_app/password_reset_form.html
{% extends 'auth_app/auth_app_base.html' %}

{% block title %}
<h2>Вкажіть Вашу адресу</h2>
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Відновити">
    <p><a href="{% url 'main_page:index' %}">На головну</a></p>
</form>
{% endblock %}