playplay/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,  name='cart_remove'),
    path('order/', views.order,  name='order'),
    path('order/confirm_order', views.confirm_order, name='confirm_order'),
]

playplay/main_page/urls.py
from django.urls import path
from . import views

app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('products_list/?<str:category>', views.products_list, name='products_list'),
    path('product/?<str:product_id>', views.product, name='product'),
    path('about_us/', views.about_us, name='about_us'),
    path('contacts/', views.contacts, name='contacts'),
]

playplay/personnel_hub/urls.py
from django.urls import path
from . import views

app_name = 'personnel_hub'
urlpatterns = [
    path('', views.index, name='personnel_hub'),
    path('products/', views.products, name='products'),
    path('products/add_new_product', views.ProductView.as_view(), name='add_new_product'),
    path('categories/', views.category, name='categories'),
    path('orders/', views.orders, name='orders'),
    path('product/edit/<int:pk>/', views.ProductChange.as_view(), name='product_edit'),
    path('product/edit/quantity/<int:pk>/', views.ProductChangeQuantity.as_view(), name='product_edit_quantity'),
]

playplay/playplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('personnel_hub/', include('personnel_hub.urls')),
    path('reg/', include('auth_app.urls')),
    path('play_games/', include('js_games.urls')),
    path('cart/', include('cart.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playplay/personnel_hub/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Назва категорії')
    description = models.TextField(verbose_name='Опис категорії')
    staff_id = models.IntegerField(blank=True, null=True, verbose_name='Ід працівника')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Назва товару')
    description = models.TextField(verbose_name='Короткий опис товару')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна за одиницю товару')
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name='Фото/картинка товару')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категорія товару')
    quantity_in_stock = models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')
    staff_id = models.IntegerField(blank=True, null=True, verbose_name='Ід працівника')
    genre = models.CharField(blank=True, null=True, max_length=100, verbose_name='Жанр')
    localization = models.CharField(blank=True, null=True, max_length=100, verbose_name='Локалізація')
    release_date = models.DateField(blank=True, null=True, verbose_name='Дата світового релізу')
    age_rating = models.CharField(blank=True, null=True, max_length=15, verbose_name='Вікові обмеження')
    system_requirements = models.TextField(blank=True, null=True, verbose_name='Рекомендовані системні вимоги')
    country_of_origin = models.CharField(blank=True, null=True, max_length=100, verbose_name='Країна-виробник')
    special_features = models.TextField(blank=True, null=True, verbose_name='Особливості')
    player_count = models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість гравців')
    publisher = models.CharField(blank=True, null=True, max_length=100, verbose_name='Видавець')
    developer = models.CharField(blank=True, null=True, max_length=100, verbose_name='Розробник')
    country_of_brand_registration = models.CharField(blank=True, null=True, max_length=100, verbose_name='Країна реєстрації бренду')

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)

    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField()


class Discount(models.Model):
    code = models.CharField(max_length=50, unique=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

playplay/personnel_hub/forms.py
from . import models
from django import forms


class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        exclude = ['staff_id']
        widgets = {
            'release_date': forms.DateInput(attrs={'type': 'date'}),
        }

class ProductChangeQuantityForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['quantity_in_stock']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = models.Category
        exclude = ['staff_id']

playplay/personnel_hub/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.views import View
from . import forms, models
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator


def is_staff(user):
    return user.is_staff


@user_passes_test(is_staff, login_url='main_page:index')
def index(request: HttpRequest):
    return render(request, 'personnel_hub/personnel_hub.html')


@method_decorator(user_passes_test(is_staff, login_url='main_page:index'), name='dispatch')
class ProductView(View):
    def get(self, request: HttpRequest):
        form = forms.ProductForm
        return render(request, 'personnel_hub/product_add_form.html', {'form': form, 'title_name': 'Продукти'})

    def post(self, request: HttpRequest):
        form = forms.ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.staff_id = request.user.id
            product.save()
            form = forms.ProductForm()
            return redirect('personnel_hub:products')
        return render(request, 'personnel_hub/product_add_form.html', {'form': form})


@user_passes_test(is_staff, login_url='main_page:index')
def products(request: HttpRequest):
    products = models.Product.objects.all()
    return render(request, 'personnel_hub/products.html', {'products': products})


@user_passes_test(is_staff, login_url='main_page:index')
def category(request: HttpRequest):
        categories = models.Category.objects.all()
        content = {'categories': categories}
        return render(request, 'personnel_hub/categories.html', content)


@user_passes_test(is_staff, login_url='main_page:index')
def orders(request: HttpRequest):
    orders_set = models.Order.objects.all()
    return render(request, 'personnel_hub/orders.html', {'orders': orders_set})


@method_decorator(user_passes_test(is_staff, login_url='main_page:index'), name='dispatch')
class ProductChangeQuantity(View):
    def get(self, request: HttpRequest, pk: int):
        product = get_object_or_404(models.Product, pk=pk)
        form = forms.ProductChangeQuantityForm(instance=product)
        context = {
            'form': form,
            'product': product,
        }
        return render(request, 'personnel_hub/product_change_form.html', context)

    def post(self, request: HttpRequest, pk: int):
        product = get_object_or_404(models.Product, pk=pk)
        form = forms.ProductChangeQuantityForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.staff_id = request.user.id
            product.save()
            return redirect('personnel_hub:products')
        else:
            context = {
                'form': form,
                'product': product,
            }
            return render(request, 'personnel_hub/product_change_form.html', context)


@method_decorator(user_passes_test(is_staff, login_url='main_page:index'), name='dispatch')
class ProductChange(View):
    def get(self, request: HttpRequest, pk: int):
        product = get_object_or_404(models.Product, pk=pk)
        form = forms.ProductForm(instance=product)
        context = {
            'form': form,
            'product': product,
        }
        return render(request, 'personnel_hub/product_add_form.html', context)

    def post(self, request: HttpRequest, pk: int):
        product = get_object_or_404(models.Product, pk=pk)
        form = forms.ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            print('ok')
            product = form.save(commit=False)
            product.staff_id = request.user.id
            product.save()
            return redirect('personnel_hub:products')
        else:
            context = {
                'form': form,
                'product': product,
            }
            return render(request, 'personnel_hub/product_add_form.html', context)

playplay/personnel_hub/templates/personnel_hub/categories.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/personnel_hub_inser_table_style.css' %}">
  <script src="{% static 'js/personel_hub_inser_table.js' %}"></script>
  <h3 align="center">Категорії</h3>
  <table>
    <thead>
      <tr>
        <th style="padding-right: 10px;">Деталі</th>
        <th style="padding-right: 10px;">Ід категорії</th>
        <th style="padding-right: 10px;">Назва</th>
        <th style="padding-right: 10px;">Опис</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
          <tr>
            <td><a href="#" onmousedown="toggleTable('nestedTable{{ forloop.counter }}', event)">Деталі</a></td>
            <td>{{ category.id }}</td>
            <td style="padding-right: 10px;">{{ category.name}}</td>
            <td>{{ category.description }} </td>
          </tr>
          <tr>
            <td colspan="5">
               <table id="nestedTable{{ forloop.counter }}" class="nested-table">
                <tr>
                  <th>Зображення</th>
                  <th style="padding-right: 10px;">Назва</th>
                  <th style="padding-right: 10px;">Платформа</th>
                  <th style="padding-right: 10px;">Залишок на складі</th>
                  <th style="padding-right: 10px;">Ціна</th>
                </tr>
                {% for item in category.product_set.all %}
                       <tr>
                     <td>
                        <a href="{% url 'main_page:product' item.id %}">
                            <img src="/media/{{ item.image }}" width=150" height="200">
                        </a>
                    </td>
                    <td style="padding-right: 10px;">{{ item.name }}</td>
                    <td>{{ item.category.name }}</td>
                    <td >{{ item.quantity_in_stock }} шт.</td>
                    <td>{{ item.price }} грн.</td>
                  </tr>
                {% endfor %}
              </table>
            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>

<a href="{% url 'personnel_hub:personnel_hub' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Повернутись</a>
{% endblock %}

{% block products %}
{% endblock %}

playplay/personnel_hub/templates/personnel_hub/orders.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/personnel_hub_inser_table_style.css' %}">
  <script src="{% static 'js/personel_hub_inser_table.js' %}"></script>
  <h3 align="center">Замовлення</h3>
  <table>
    <thead>
      <tr>
        <th style="padding-right: 10px;">Деталі</th>
        <th style="padding-right: 10px;">Ід замовлення</th>
        <th style="padding-right: 10px;">Дата замовлення</th>
        <th style="padding-right: 10px;">Клієнт</th>
        <th style="padding-right: 10px;">Сума замовлення</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
          <tr>
            <td><a href="#" onmousedown="toggleTable('nestedTable{{ forloop.counter }}', event)">Деталі</a></td>
            <td>{{ order.id }}</td>
            <td>{{ order.order_date|date:"d-m-Y"}}</td>
            <td style="padding-right: 10px;">{{ order.user.email }} </td>
            <td>{{ order.total_amount }} грн. </td>
          </tr>
          <tr>
            <td colspan="5">
               <table id="nestedTable{{ forloop.counter }}" class="nested-table">
                <tr>
                  <th>Зображення</th>
                  <th style="padding-right: 10px;">Назва</th>
                  <th style="padding-right: 10px;">Платформа</th>
                  <th style="padding-right: 10px;">Кількість</th>
                  <th style="padding-right: 10px;">Ціна</th>
                </tr>
                {% for item in order.orderitem_set.all %}
                       <tr>
                     <td>
                        <a href="{% url 'main_page:product' product_id=item.product.id %}">
                            <img src="{{ item.product.image.url }}" width=150" height="200">
                        </a>
                    </td>
                    <td style="padding-right: 10px;">{{ item.product.name }}</td>
                    <td>{{ item.product.category.name }}</td>
                    <td>{{ item.quantity }} шт.</td>
                    <td>{{ item.product.price }} грн.</td>
                  </tr>
                {% endfor %}
              </table>
            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
<a href="{% url 'personnel_hub:personnel_hub' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Повернутись</a>
{% endblock %}

{% block products %}
{% endblock %}

playplay/personnel_hub/templates/personnel_hub/personnel_hub.html
{% extends 'main_page/index.html' %}
{% load static %}


    {% block categories %}
    <section class="u-align-center u-clearfix u-palette-3-base u-section-1" id="sec-f7d1">
      <div class="u-clearfix u-gutter-0 u-layout-wrap u-layout-wrap-1">
        <div class="u-gutter-0 u-layout">
          <div class="u-layout-row">
            <div class="u-container-align-left u-container-style u-layout-cell u-shape-rectangle u-size-22-xl u-size-26-lg u-size-60-md u-size-60-sm u-size-60-xs u-layout-cell-2">
              <div class="u-container-layout u-valign-middle u-container-layout-2">
                <h2 class="u-align-left u-text u-text-1" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="250"> Доступні інструменти</h2>
                <div class="u-expanded-width-lg u-expanded-width-xl u-list u-list-1">
                  <div class="u-repeater u-repeater-1">
                    <div class="u-container-align-left u-container-style u-list-item u-repeater-item u-list-item-1" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500">
                      <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-3">
                        <h6 class="u-align-left u-text u-text-default u-text-3"><span class="u-file-icon u-icon u-icon-1"><img src="{% static 'css/images/711239.png' %}" alt=""></span>&nbsp;
                            <li class="u-nav-item">
                                <a class="u-button-style u-nav-link" href="{% url 'personnel_hub:categories' %}">Переглянд категорій</a>
                            </li>
                        </h6>
                      </div>
                    </div>
                    <div class="u-container-align-left u-container-style u-list-item u-repeater-item u-list-item-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500">
                      <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-4">
                        <h6 class="u-align-left u-text u-text-default u-text-4"><span class="u-file-icon u-icon u-icon-2"><img src="{% static 'css/images/711239.png' %}" alt=""></span>&nbsp;
                            <li class="u-nav-item">
                                <a class="u-button-style u-nav-link" href="{% url 'personnel_hub:products' %}">Робота з товарами</a>
                            </li>
                        </h6>
                      </div>
                    </div>
                    <div class="u-container-align-left u-container-style u-list-item u-repeater-item u-list-item-3" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500">
                      <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-5">
                        <h6 class="u-align-left u-text u-text-default u-text-5"><span class="u-file-icon u-icon u-icon-3"><img src="{% static 'css/images/711239.png' %}" alt=""></span>&nbsp;
                            <li class="u-nav-item">
                                <a class="u-button-style u-nav-link" href="{% url 'personnel_hub:orders' %}">Переглянути замовлення</a>
                            </li>
                        </h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block products %}
    {% endblock %}

playplay/personnel_hub/templates/personnel_hub/product_add_form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Product Details</title>
  <link rel="stylesheet" href="{% static 'css/game_styles.css' %}">
</head>

{% block content %}
<body>
  <div class="top-left-links">
    <a href="{% url 'main_page:index' %}">Головна</a>
    <a href="{% url 'personnel_hub:personnel_hub' %}">Для персоналу</a>
  </div>
  <h1 align="center">{{ title_name }}</h1>
  <div class="container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Внести запис до бази</button>
    </form>
  </div>
</body>
{% endblock %}

playplay/personnel_hub/templates/personnel_hub/product_change_form.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
<body>
  <div class="container">
    <h3 align="center">Внести на склад</h3>
        <table class="cart">
        <thead>
            <tr>
        <th>Зображення</th>
        <th style="padding-right: 10px;">Назва</th>
        <th style="padding-right: 10px;">Залишок</th>
      </tr>
    </thead>
    <tbody>
       <tr>
            <td>
              <a href="{% url 'main_page:product' product.id %}">
                <img src="{{ product.image.url }}" width=150" height="200">
              </a>
            </td>
           <td>
               {{ product.name }}
           </td>
           <td>
               <form method="post">
                    {% csrf_token %}
                    {{ form.quantity_in_stock }}
                    <button type="submit">Зберегти зміни</button>
               </form>
           </td>
       </tr>
    </tbody>
        </table>
  </div>
</body>
{% endblock %}


{% block products %}
{% endblock %}

playplay/personnel_hub/templates/personnel_hub/products.html
{% extends 'main_page/index.html' %}
{% load static %}

{% block categories %}
{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/personnel_hub_inser_table_style.css' %}">
  <script src="{% static 'js/personel_hub_inser_table.js' %}"></script>
  <h3 align="center">Товари/Склад</h3>
<hr>
  <table>
    <tbody>
          <tr>
            <td><a href="#" onmousedown="toggleTable('nestedTable{{ forloop.counter }}', event)">Товари, що закінчились</a></td>
          </tr>
          <tr>
            <td colspan="5">
               <table id="nestedTable{{ forloop.counter }}" class="nested-table">
                <tr>
                  <th>Зображення</th>
                  <th style="padding-right: 10px;">Назва</th>
                  <th style="padding-right: 10px;">Платформа</th>
                  <th style="padding-right: 10px;">Залишок на складі</th>
                  <th style="padding-right: 10px;">Ціна</th>
                </tr>
                {% for product in products %}
                   {% if product.quantity_in_stock == 0 %}
                       <tr>
                     <td>
                        <a href="{% url 'main_page:product' product.id %}">
                            <img src="{{ product.image.url }}" width=150" height="200">
                        </a>
                    </td>
                    <td style="padding-right: 10px;">{{ product.name }}</td>
                    <td style="padding-right: 10px;">{{ product.category.name }}</td>
                    <td style="padding-right: 10px;">{{ product.quantity_in_stock }} шт.</td>
                    <td style="padding-right: 10px;">{{ product.price }} грн.</td>
                    <td >
                        <a href="{% url 'personnel_hub:product_edit_quantity' product.id %}">Добавити на склад</a>
                    </td>
                  </tr>
                   {% endif %}
                {% endfor %}
              </table>
                <hr>
            </td>
          </tr>

          <tr>

            <td><a href="#" onmousedown="toggleTable('nestedTable2{{ forloop.counter }}', event)">Товари, що закінчуються</a></td>
          </tr>
          <tr>
            <td colspan="5">
               <table id="nestedTable2{{ forloop.counter }}" class="nested-table">
                <tr>
                  <th>Зображення</th>
                  <th style="padding-right: 10px;">Назва</th>
                  <th style="padding-right: 10px;">Платформа</th>
                  <th style="padding-right: 10px;">Залишок на складі</th>
                  <th style="padding-right: 10px;">Ціна</th>
                </tr>
                {% for product in products %}
                   {% if product.quantity_in_stock > 0 and product.quantity_in_stock <= 20 %}
                       <tr>
                     <td>
                        <a href="{% url 'main_page:product' product.id %}">
                            <img src="{{ product.image.url }}" width=150" height="200">
                        </a>
                    </td>
                    <td style="padding-right: 10px;">{{ product.name }}</td>
                    <td>{{ product.category.name }}</td>
                    <td >{{ product.quantity_in_stock }} шт.</td>
                    <td>{{ product.price }} грн.</td>
                    <td >
                        <a href="{% url 'personnel_hub:product_edit_quantity' product.id %}">Добавити на склад</a>
                    </td>
                  </tr>
                   {% endif %}
                {% endfor %}
              </table>
                <hr>
            </td>
          </tr>

           <tr>

            <td><a href="#" onmousedown="toggleTable('nestedTable3{{ forloop.counter }}', event)">Всі товари</a></td>
          </tr>
          <tr>
            <td colspan="5">
               <table id="nestedTable3{{ forloop.counter }}" class="nested-table">
                <tr>
                    <th style="padding-right: 10px;">Картинка</th>
                    <th style="padding-right: 10px;">Ід товару</th>
                    <th style="padding-right: 10px;">Назва</th>
                    <th style="padding-right: 10px;">Платформа</th>
                    <th style="padding-right: 10px;">Залишок на складі</th>
                    <th style="padding-right: 10px;">Ціна</th>
                </tr>
                {% for product in products %}
                    <tr>
                        <td>
                            <a href="{% url 'main_page:product' product.id %}">
                                <img src="/media/{{ product.image }}" width=150" height="200">
                            </a>
                        <td>{{ product.id }}</td>
                        <td>{{ product.name}}</td>
                        <td>{{ product.category.name }} </td>
                        <td>{{ product.quantity_in_stock }} шт. </td>
                        <td>{{ product.price }} грн. </td>
                        <td >
                        <a href="{% url 'personnel_hub:product_edit' product.id %}">Внести зміни</a>
                    </td>
                    </tr>
                {% endfor %}
              </table>
                <hr>
            </td>
          </tr>
    </tbody>
  </table>
<a href="{% url 'personnel_hub:add_new_product' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Внести новий товар</a>
<a href="{% url 'personnel_hub:personnel_hub' %}" class="u-active-palette-3-base u-align-left u-black u-border-2 u-border-active-black u-border-black u-border-hover-black u-border-radius-50 u-btn u-btn-round u-button-style u-hover-palette-3-base u-btn-2" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750">Повернутись</a>

{% endblock %}

{% block products %}
{% endblock %}